spring:
  application:
    name: woory

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  profiles:
    default: prod
    include:
      - secret
    group:
      prod:
        - prod
      local:
        - local
      dev:
        - dev

springdoc:
  api-docs:
    path: /swagger/docs
  swagger-ui:
    url: /swagger/docs