name: push feat to dev

on:
  pull_request:
    branches: [ feat ]
    types: [ closed ]
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # feat 변경사항 dev로 이동
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0
      - run: |
          # remote url 변경
          git config remote.origin.url "https://$TOKEN@github.com/$REPOSITORY.git"
          
          # 실제 push 작업 수행
          git push origin feat:dev
        env:
          TOKEN: x-access-token:${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: SWYP-Woory/woory-backend