name : push feat to dev

on:
  pull_request:
    branches: [ dev ]
    types: [ closed ]
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # feat 브랜치로 이동
      - name: Checkout to feat
        uses: actions/checkout@v4.2.2
        with:
          ref: feat
          persist-credentials: false
          fetch-depth: 0
      # feat -> dev 브랜치로 push
      - name: Push changes to dev
        uses: actions-js/push@v1.5
        with:
          branch: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}