name: push feat to dev

on:
  pull_request:
    branches: [ feat ]
    types: [ closed ]
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # feat 변경사항 dev로 이동
      - uses: actions/checkout@v4.2.2

      - name: push feat to dev
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: SWYP-Woory/woory-backend
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          
          # remote url 변경
          echo "setting remote origin address"
          git remote set-url origin "https://x-access-token:$TOKEN@github.com/$REPOSITORY.git"
          echo "setting address to: 'https://x-access-token:$TOKEN@github.com/$REPOSITORY.git'"
          git remote -v
          
          git fetch origin
          
          git log --oneline
          
          git pull origin feat
          
          git log --oneline
          
          # 실제 push 작업 수행
          echo "pushing feat to dev"
          git push origin dev
